FROM node:18-alpine3.18

WORKDIR /app

COPY package.json package.json
COPY yarn.lock yarn.lock
RUN yarn install --immutable --immutable-cache --check-cache

COPY ./ ./
ENV CI=1
CMD [ "yarn", "expo", "start", "--no-dev", "--minify" ]
