version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      EXPO_PACKAGER_PROXY_URL:
      EXPO_PUBLIC_GOOGLE_MAP_API_KEY:
      EXPO_PUBLIC_API_BASE_URL:
  backend-mock:
    build:
      context: mock
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY:
